### PR TITLE
Update Loom to Python 3.

### PR DESCRIPTION
**Pull request by emilyfertig**
All unit tests pass, except those dependent on `parsable` and `goftests`, which need to be updated to py3. This PR does not include updates the `examples` directory, which depends on `parsable`. An outstanding issue is that `pool.starmap` hangs (in Python multiprocessing).

### CODE REVIEW

**Comment by emilyfertig** [comment]
(I wanted to send this PR to a new branch and not to `master`, but it looks like I can't do that unless someone with the right permissions creates a new branch first.)

**Comment by fritzo** [comment]
Wow props for this serious maintenance effort! 💯 

I've created a [python-3](https://github.com/posterior/loom/tree/python-3) branch, but actually I think it's best to make this PR directly to master. To track the legacy version, I've also created a [python-2](https://github.com/posterior/loom/tree/python-2) branch which we can keep at the old version.

In the meantime, let me take a look at `parsable` and `goftests` to see if I can get those working in Python 3.

**Comment by fritzo** [comment]
@emilyfertig I've also sent you an invite to the Developers group, so you should be able to create new branches, push, etc.

**Comment by emilyfertig** [comment]
@fritzo thank you! I have a PR in the works for `distributions`, I'll try to send it early next week.

**Comment by fritzo** [comment]
Re: distributions, it be easiest to switch from nose to pytest.

**Comment by emilyfertig** [comment]
I sent a PR to `distributions` that leaves in `nose` for now. If you want, I can send a followup that gets rid of it and uses `pytest` exclusively.

The installation instructions didn't work for me as-is and I had to make some changes to `CMakeLists` and `Makefile`, and append a couple things to `PATH` (this is on Google's internal version of Linux, so I'm not sure how universally necessary these changes are). If someone wants to work on updating the installation instructions, I'm happy to share what I did (in particular, I suspect that something might have changed in `virtualenvwrapper` that changed the location of certain files).

Do you think we should still merge this directly to master before updating the installation instructions etc., or is it better to work on that in a separate branch?

**Comment by fritzo** [comment]
> updating the installation instructions...

Kudos for getting loom to build! Maybe the most maintainable solution would be to replace the install instructions with a Dockerfile that can be tested by a .github/workflows/ci.yml. The [old dockerfile](https://github.com/posterior/loom/blob/master/docker/ubuntu1604) runs on an unmaintained ubuntu image. 

> Do you think we should still merge this directly to master

Yes, let's just work directly in the master branch. Last commit was 7 years ago, and there are stable tags, so we shouldn't break anyone's code. Once the upstream dependencies are released, we can tag and release.

Would you like to merge this now, or wait until all tests pass?

**Comment by fritzo** [comment]
@emilyfertig Thanks for your [comment](https://github.com/posterior/distributions/pull/18#issuecomment-1955420557) with the parsable bug. I've fixed parsable, strengthened the tests, and pushed a release (0.3.1).

**Comment by emilyfertig** [comment]
All tests (and examples) are now passing with the updated `parsable`, so I think this is in a good state to merge.

A remaining issue on the Python side is that I haven't been able to get multiprocessing to work (see `util.parallel_map`). It has something to do with `CategoricalEncoderBuilder.__setstate__` and multiprocessing's use of `pickle`, I think:

```
Running _make_encoder_builders_file in 12 threads
Exception in thread Thread-9 (_handle_results):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CategoricalEncoderBuilder.__setstate__() missing 2 required positional arguments: 'model' and 'counts'
^CProcess ForkPoolWorker-35:
Process ForkPoolWorker-30:
Process ForkPoolWorker-31:
Process ForkPoolWorker-26:
Process ForkPoolWorker-29:
Process ForkPoolWorker-36:
Process ForkPoolWorker-27:
Process ForkPoolWorker-33:
Process ForkPoolWorker-32:
Process ForkPoolWorker-28:
Process ForkPoolWorker-34:
Process ForkPoolWorker-25:
Traceback (most recent call last):
  File "/usr/local/google/home/emilyaf/posterior_loom/loom/examples/lending_club/main.py", line 378, in <module>
    parsable.dispatch()
  File "/usr/local/google/home/emilyaf/.virtualenvs/loom/lib/python3.11/site-packages/parsable.py", line 139, in dispatch
    parser(*args, **kwargs)
  File "/usr/local/google/home/emilyaf/.virtualenvs/loom/lib/python3.11/site-packages/parsable.py", line 72, in parser
    fun(*typed_args, **typed_kwargs)
  File "/usr/local/google/home/emilyaf/posterior_loom/loom/examples/lending_club/main.py", line 373, in test
    run(sample_count=2)
  File "/usr/local/google/home/emilyaf/posterior_loom/loom/examples/lending_club/main.py", line 359, in run
    ingest()
  File "/usr/local/google/home/emilyaf/posterior_loom/loom/examples/lending_club/main.py", line 166, in ingest
    loom.tasks.ingest(NAME, id_field='id')
  File "/usr/local/google/home/emilyaf/.virtualenvs/loom/lib/python3.11/site-packages/loom/tasks.py", line 138, in ingest
    loom.format.make_encoding(
  File "/usr/local/google/home/emilyaf/.virtualenvs/loom/lib/python3.11/site-packages/loom/format.py", line 287, in make_encoding
    builders = _make_encoder_builders_dir(schema_in, rows_in)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/emilyaf/.virtualenvs/loom/lib/python3.11/site-packages/loom/format.py", line 256, in _make_encoder_builders_dir
    partial_builders = loom.util.parallel_map(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/emilyaf/.virtualenvs/loom/lib/python3.11/site-packages/loom/util.py", line 165, in parallel_map
    return pool.starmap(print_trace, fun_args, chunksize=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/threading.py", line 327, in wait
    waiter.acquire()
KeyboardInterrupt
```

I wonder if multithreading instead of multiprocessing would be appropriate here, since we're usually looking to parallelize cpp subprocesses, which release the GIL. I can look at sending a PR for multithreading if you want.

I had to make extensive hacky changes to Makefile and CMakeLists to get it to build. I'll upload those elsewhere for reference.

**Pull request merged**
